# Generated by Django 5.1.7 on 2025-03-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=255)),
                ('singer', models.CharField(max_length=255)),
                ('movie', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(max_length=100)),
                ('song_url', models.URLField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
